from odoo import api, fields, models, SUPERUSER_ID, _
from datetime import date
from odoo.exceptions import UserError, ValidationError, MissingError


class BundleTherapyBarem(models.Model):
    _name = 'bundle.therapy.barem'

    name = fields.Char(string='Bundle Therapy Barem')
    value_bundle_max = fields.Char(string='Value Bundle Max')
    value_bundle_min = fields.Char(string='Value Bundle Min')
    qty_medicine_day_max = fields.Integer(string='Medicine Day Max')
    bundle_therapy_barem_line_ids = fields.One2many('bundle.therapy.barem.line', 'bundle_therapy_barem_id', string='Bundle Line')
    product_id = fields.Many2one('product.product', string='Service medicine')
    qty_max = fields.Integer
    active = fields.Boolean(default=True)


class BundleTherapyBaremLine(models.Model):
    _name = 'bundle.therapy.barem.line'

    name = fields.Char(string='Bundle Therapy Barem Line')
    product_id = fields.Many2one('product.product', string='Product')
    uom_id = fields.Many2one('product.uom', string='Unit of  Measure', required=True)
    qty = fields.Integer(string='Qty')
    note = fields.Char(string='Note')
    bundle_therapy_barem_id = fields.Many2one('bundle.therapy.barem')

    @api.onchange('product_id')
    def _onchange_product_id(self):
        if self.product_id:
            self.uom_id = self.product_id.product_tmpl_id.uom_id.id

